[profile.default]
src = 'src'
test = 'tests'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'solidity-utils/=lib/solidity-utils/src/',
    'chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
