[profile.default]
src = 'src'
test = 'tests'
out = 'out'
libs = ['lib']
gas_reports = ["ProofOfReserveExecutorV2"]
script = 'scripts'
remappings = []
ffi = true

[fuzz]
runs = 1024
max_test_rejects = 1000000

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"

[etherscan]
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chainId=43114}

# See more config options https://github.com/gakonst/foundry/tree/master/config
