[profile.default]
src = 'src'
test = 'tests'
out = 'out'
libs = ['lib']
gas_reports = ["ProofOfReserveExecutorV2"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    'solidity-utils/=lib/solidity-utils/src/',
    'chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/contracts/src/v0.8/',
    'aave-address-book/=lib/aave-address-book/src/',
    'aave-helpers/=lib/aave-helpers/src/',
    '@aave/core-v2=lib/protocol-v2/'
]
[rpc_endpoints]
ethereum="${RPC_ETHEREUM}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"

# See more config options https://github.com/gakonst/foundry/tree/master/config
